#!/bin/bash

S="ubuntu@54.187.78.39"

function server {
    ssh -t $S "$1"
}

# fix random string function return some value
random-string(){
    cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1
}

if [ $# -eq 0 ]
then
    server
    exit
fi

case "$1" in
    install)
        server "sudo apt-get install $2"
        ;;
    update)
        server "sudo apt-get update"
        ;;
    dl)
        server "youtube-dl $2 -o /home/ubuntu/a.mp4"
        NEW_NAME=$(cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
        scp $S:/home/ubuntu/a.mp4 ~/Downloads/$NEW_NAME.mp4
        open ~/Downloads/$NEW_NAME.mp4
        ;;
    *)
        echo "not support option '$1' yet"
esac
